# Site settings
title: Nisarg Pathak
twitter_username: npp07
name: Nisarg Pathak

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://nisargpathak.blogspot.in/
 - title: GitHub
   url: https://github.com/npjava90
 - title: LinkedIn
   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
 - Spring MVC
 - Spring Boot
 - MicroServices
 - Hibernate
 - Java
 - SQL
 - SOAP
 - REST
 - Angularjs

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://nisargpathak.blogspot.com/feeds/posts/default?alt=rss

#Work experience is required
roles:
 - title: Software Developer
   start: 2016
   end: Ongoing
   employer: Oracle Financial Software Services Private Limited
   description:OBP (Oracle Banking Platform) acts as a Middleware between Netbanking and Flexcube.The project is developed         using Soap Web Services.Webservices are deployed in WebLogic Server & Logging of errors in application is achieved by Log4j.Hands on experience in soap webservices ,weblogic server & deployment,JMS.

 - title: Software Developer
   start: 2015
   end: 2016
   employer: Covestor
   description: Merchant Onboarding Application is developed based on Struts and Spring Framework.project is used to automate Merchant onboarding process.Hands on experience in development using Struts & spring for dependancy injetion ,AngularJS & JBoss server.
 - title: Junior Software Developer
   start: 2015
   end: 2016
   employer: Insolutions Global Private Limited
   description: A range of technical roles, primarily working on client sites in Financial Services.

#Education is required
education:
 - level:Maser of Computer Application (M.C.A)
   date: 2013
   subject: Computer Science
   school: University of Gujarat

#This section is optional (as is the image link below)
Udemy:
   profileurl: https://www.udemy.com/user/nisarg-prakash-chandra-pathak
   courses:
    - title: Mastering microservices with spring-boot & spring-cloud
      link: https://www.udemy.com/microservices-with-spring-boot-and-spring-cloud
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: December 16, 2017
  
#List of interesting Github repo/projects to include - optional
github:
 - npjava90/SpringConfigServer
- npjava90/Config
- npjava90/SpringBootRestService
- npjava90/MicroSpringCloud
- npjava90/SpringBatchXmlParsing
- npjava90/JerseyHateOas
- npjava90/SpringWithAngular
- npjava90/spring_ultiple_fileupload
- npjava90/struts_jasper
- npjava90/Spring-Batch-Zip-Generation

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java APIâ€™s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>). <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
